[[local-agent]]
path = "agents/predict0-agent"

[[local-agent]]
path = "agents/predict1-agent"

[[local-agent]]
path = "agents/predict2-agent"

[[local-agent]]
path = "agents/interface"

[[local-agent]]
path = "agents/firecrawl"