[agent]
name = "interface"
version = "0.0.1"
description = "Agent designed to interface with the end user"

[options.USER_REQUEST]
type = "string"
required = true
description = "The user request to fulfill"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
