[agent]
name = "predict0"
version = "1.0.0"

[options.MODEL_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4.1')"
default = "mistral-small-2506"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
